# Generated by Django 4.2.8 on 2023-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='professional_page',
            field=models.BooleanField(default=False),
        ),
    ]
