# Generated by Django 4.2.8 on 2023-12-22 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2023, 12, 22, 13, 20, 53, 757224, tzinfo=datetime.timezone.utc), max_length=25),
            preserve_default=False,
        ),
    ]
